baseurl = "https://www.atopowe.pl"
language-code = "pl-pl"
copyright = "2003-2016 Atopowe.pl"
title = "Atopowe Zapalenie Skóry"
[permalinks]
  post = "/:year/:month/:day/:slug/"
[taxonomies]
  rodzajkosmetyku = "rodzajekosmetykow"
  rodzajprzepisu = "rodzajeprzepisow"
  kategoria = "kategorie"
  rodzajleku = "rodzajelekow"
[params]
  logo = "/images/atopowe-logo.png"
  googleplus = "https://plus.google.com/+AtopowePL"
  twitter = "https://twitter.com/atopowe"
  description = "Forum oraz FAQ, informacje oraz porady pochodzące od osób chorych na AZS."
  # githubsrc jest używane do "edytuj tę stronę"
  githubsrc = "https://github.com/automatthias/atopowe-hugo/blob/master/content/"
