baseurl = "https://www.atopowe.pl"
language-code = "pl-pl"
copyright = "2003-2016 Atopowe.pl"
title = "Atopowe Zapalenie Skóry"
[permalinks]
  post = "/:year/:month/:day/:slug/"
[taxonomies]
  rodzajkosmetyku = "rodzajekosmetykow"
  rodzajprzepisu = "rodzajeprzepisow"
  kategoria = "kategorie"
  rodzajleku = "rodzajelekow"
[params]
  logo = "/images/atopowe-logo.png"
  googleplus = "https://plus.google.com/+AtopowePL"
  twitter = "https://twitter.com/atopowe"
  # Opis strony. Pojawia się on w kilku miejscach na stronie i jest to opis
  # prezentowany wyszukiwarkom jako najbardziej podstawowa informacja, czym jest
  # atopowe.pl.
  description = "Atopowe.pl jest stroną poświęconą atopowemu zapaleniu skóry, alergii, atopii i astmie."
  # githubsrc jest używane do "edytuj tę stronę"
  githubsrc = "https://github.com/automatthias/atopowe-hugo/blob/master/content/"
