title: "Atopowe Zapalenie Skóry"
baseurl: https://www.atopowe.pl
language-code: pl-pl
copyright: 2003-2016 Atopowe.pl
params:
  logo: /images/atopowe-logo.png
  description: "Forum oraz FAQ, informacje oraz porady pochodzące od osób chorych na AZS."
  twitter: "https://twitter.com/atopowe"
permalinks:
  post: /:year/:month/:day/:slug/
taxonomies:
  kategoria: "kategorie"
