url: http://blog.atopowe.pl
baseurl: http://localhost:1313
language-code: pl-pl
name: Blog Atopowy
description: >
  Nowiny, relacje, przemyślenia
  (skomentowane)
theme: "hugo-zen"
copyright: 2003-2016 Atopowe.pl
